### ISSUE TITLE
Proposal: allow to type and draw numbers

### ISSUE THREAD

**Issue by RadRussianRus** [maaslalani/draw#11]
**Is your feature request related to a problem? Please describe.**
Since color is currently selected by 1-9 keys, it's impossible to type these numbers as text or draw with them.

**Describe the solution you'd like**
When pressing 1-9 key, it should be allowed to type them instead of changing color. Of course, a question arises: how to change color? I've did some tests, and keys Alt+1 up to Alt+9 worked fine for me, so I'm proposing to move color switching to them instead.

Here's how it could look:
```go
case "alt+1", "alt+2", "alt+3", "alt+4", "alt+5", "alt+6", "alt+7", "alt+8", "alt+9":
	m.color = msg.String()[len(msg.String())-1:] // last symbol is number we need
```

**Describe alternatives you've considered**
There are other ways to approach this:

* **Make Alt+number keys to type/select the number.** However, it's inconvenient for typing.
* **Use other hotkeys for color selection.** Not sure what hotkeys could be used though because Ctrl+number gives unexpected results (like `Ctrl+@` when you're trying to type `Ctrl+2`), and Shift+number are used to typing special characters.

**Comment by maaslalani** [comment]
Ah I wish I thought about this a little more and went with <kbd>Alt+[1234]</kbd> or <kbd>Alt+[rbgy]</kbd> for color picking instead of using simply the numbers but I figured that not many people would need the numbers to draw with since you can now type them out when in "insert" mode.

I think the <kbd>Alt+[1234]</kbd> is reasonable, I'd accept a PR for that change if you want to contribute to the project or I can add the changes myself, let me know :)

**Comment by maaslalani** [comment]
Also, thanks for the well-written + well-thought issue. I really appreciate it ❤️
